from unittest import TestCase
from pathlib import Path
from xplane_airports.AptDetail import DetailedAirport

class TestAptDetail(TestCase):
    def setUp(self):
        self.apt_dat_single_string = """I
                        1000 Generated by WorldEditor

                        1    695 1 0 EDX6 Schwalmstadt Ziegenhain
                        100 30.00 3 0 0.00 0 0 0 14  50.90432000  009.23853100    0    0 1 0 0 0 32  50.89749800  009.24514000    0    0 1 0 0 0
                        100 30.00 3 0 0.00 0 0 0 03  50.90159600  009.23946100    0    0 1 0 0 0 21  50.90923600  009.24563000    0    0 1 0 0 0
                        110 1 0.00 0.0000 Asphalt paths
                        111  50.90234299  009.24281174
                        99
                        """

        self.apt_dat_single_string1 = """I
                            1130 Generated by WorldEditor

                            1     20 1 0 KBOS Boston Logan Intl
                            100 46.02 1 1 0.00 1 3 1 15R  42.37428432 -071.01792575  268   61 3 8 1 0 33L  42.35466419 -070.99162135    0   53 3 8 1 0
                            100 46.02 1 1 0.00 1 3 1 04L  42.35800046 -071.01437574    0    0 3 0 0 2 22R  42.37830380 -071.00455234  248   61 3 0 0 0
                            100 46.02 1 1 0.00 1 3 1 04R  42.35107249 -071.01183012  352    0 3 2 1 0 22L  42.37691354 -070.99932612  365   61 3 9 0 0
                            100 46.02 1 1 0.00 1 3 1 09  42.35576765 -071.01292865    0    0 3 0 0 0 27  42.36023032 -070.98773848    0   49 3 0 0 1
                            100 29.87 1 1 0.00 0 2 0 15L  42.37359269 -071.00916205    0   30 2 0 0 0 33R  42.36861510 -071.00249217    0   30 2 0 0 0
                            100 29.87 1 0 0.00 0 3 1 14  42.35661149 -071.02331027    0    0 2 0 0 0 32  42.34861319 -071.00828089    0  244 3 0 1 1
                            110 2 0.00 257.3300 Concrete Pad Hangar
                            111  42.36509655 -071.00267196
                            99
                           """

        self.apt_dat_multi_string = """A
                                1234 Generated by WorldEditor

                                1   2084 0 0 YTWB Toowoomba
                                100 29.87 1 0 0.25 0 2 0 11 -27.54021531  151.91198836    0    0 2 0 1 0 29 -27.54021533  151.92212245    0    0 2 0 1 0
                                100 49.99 15 0 0.25 0 0 0 07 -27.54417182  151.91052007    0    0 0 0 0 0 25 -27.54206566  151.91805380    0    0 0 0 0 0
                                1302 icao_code YTWB
                                110 2 1.00 190.0000 New Taxiway 13
                                111 -27.54381636  151.91715300
                                111 -27.54388400  151.91714277
                                111 -27.54390957  151.91731210
                                1200 Taxi network
                                1201 47.54 -122.308 both 5416 A_start
                                1000 Calm and south flows
                                1001 YTWB 000 359 5

                                1     39 0 0 SDCR Fazenda Caicara
                                100 17.98 5 0 0.00 0 0 0 09 -24.06946550 -046.82978069    0    0 0 0 0 0 27 -24.06748020 -046.82470758    0    0 0 0 0 0
                                110 4 0.00 0.0000 Dirtway
                                112 -24.06984901 -046.83011229 -24.06987583 -046.83011229
                                112 -24.07008327 -046.83006415 -24.07010219 -046.83004461
                                112 -24.07014133 -046.82997383 -24.07016201 -046.82995406
                                112 -24.07086622 -046.82960021 -24.07088131 -046.82959287

                                1    978 1 0 SCVO Maria Ester
                                100 20.12 3 0 0.00 0 0 0 06 -38.23172467 -072.48881639    0    0 1 0 0 0 24 -38.23021033 -072.48162169    0    0 1 0 0 0
                                110 3 0.25 75.0000 Base grass
                                111 -38.23230963 -072.49005050
                                111 -38.23036611 -072.48081362
                                111 -38.22980450 -072.48098277


                                1   1235 0 0 YTNK Tennant Creek
                                100 29.87 1 0 0.25 0 1 0 07 -19.63589237  134.16954220    0    0 2 0 0 0 25 -19.63113463  134.18751318    0    0 2 0 0 0
                                100 17.98 1 1 0.25 0 1 0 11 -19.63383181  134.17579223    0    0 1 0 0 0 29 -19.63848096  134.18455258    0    0 1 0 0 0
                                100 11.89 1 0 0.25 0 0 0 2 -19.63780860  134.18404058    0    0 1 0 0 0 20 -19.63169996  134.18683776    0    0 1 0 0 0
                                110 1 1.00 74.3000 New Taxiway 2
                                111 -19.63151194  134.18661256
                                111 -19.63157860  134.18668333
                                99
                                """

        self.multi_parser = DetailedAirport.from_file_text(self.apt_dat_multi_string, 'foo.dat')
        self.single_parser = DetailedAirport.from_file_text(self.apt_dat_single_string, 'bar.dat')[0]
        self.single_parser1 = DetailedAirport.from_file_text(self.apt_dat_single_string1, '')[0]
        self.single_parser_from_multi = self.multi_parser["sCvO"]

    #######################################
    # Tests for the multi-apt.dat parser
    #######################################
    def test_versions(self):
        self.assertEqual(self.multi_parser.xplane_version, 1242)
        for apt in self.multi_parser:
            self.assertEqual(apt.xplane_version, self.multi_parser.xplane_version)

